### PR TITLE
fix: remove plan from report if comment is too long

### LINKED ISSUE #17: Check fails if comment is too long
If comment is too long i.e. more than 65536 characters, check will fail with this error:
```
Unhandled error: HttpError: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}
```

As the culprit usually is the terraform plan result, I think we can make it to still post comment without the terraform plan result and tell users to check workflow run summary to find the complete result.

### PR DESCRIPTION
**Pull request by FurqanHabibi**
Tested.

Closes #17

### CODE REVIEW

**Review by hanscg — COMMENTED** [review]
Thank you for working on this!
Do you think it's possible to remove the plan only from the PR comment but keep it in the workflow job summary?

The documentation says the limit for job summary is 1MB, which might be long enough for plans that are too long for the comments.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#step-isolation-and-limits

**Comment by FurqanHabibi** [comment]
@hanscg Kept the full report posted as job summary 🙏

**Review by hanscg — COMMENTED** [review]
Could you update the comment to say something like 
"The plan is not output here because it's too long, check the workflow summary for full check result"

**Review by hanscg — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
